name: awersome_list
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  built_collection: '>=2.0.0 <5.0.0'
  built_value: '>=5.5.5 <7.0.0'
  url_launcher: ^5.0.1
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^6.3.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true